apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - namespaces
  - sources
  - metrics-server
  - istio-base
  - istiod
  - prometheus
  - grafana
  - kiali
  - aspire
