apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  - .helm-repos
  - crds
  - namespaces
  - metrics-server
  - istio-base
  - istiod
  - prometheus
  - grafana
  - kiali
  - aspire
