apiVersion: v1
kind: Service
metadata:
  name: aspire
  namespace: monitor
  labels:
    app:  aspire
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 18888
    protocol: TCP
    name: aspire-dashboard
  - port: 18889
    targetPort: 18889
    protocol: TCP
    name: aspire-export
  selector:
    app: aspire